version: "2"
services:
  mongo:
    image: mongo:latest
    volumes:
      - /data/db
    ports:
      - 27017
  redis:
    image: redis:alpine
    ports:
      - 6379
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    links:
      - locker
    ports:
      - 80:80
  locker:
    build:
      context: .
      dockerfile: Dockerfile.locker
    environment:
      - MONGODB_PATH=mongodb://mongo:27017/learninglocker_v2
      - ADMIN_EMAIL
      - ADMIN_ORGANISATION
      - ADMIN_PASSWORD
      - SMTP_HOST=smtp
      - APP_SECRET
    links:
      - mongo
      - redis
      - smtp
    ports:
      - 3000
      - 8080
  smtp:
    image: tecnativa/smtp-sink
    ports:
      - 25
